### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by lukasberlin** [Strider-CD/strider-bitbucket#15]
In the beginning I used the plugin just to import my bitbucket projects into strider. After a while I found the possibility to use Webhooks to trigger the Strider jobs. I configured the environment variables and looked for a possibility to add the hooks using the plugin and couldn't find it. So I tried to start from scratch. I reset the complete Strider DB and imported my BitBucket account again. This worked, the plugin automatically created a Webhook in BitBucket and the job is triggered on commits.

Is it possible to just create the Webhook without resetting the complete DB, using the plugin or is it possible to find the URL that has to be used for the Webhook in order to trigger the job, so that I can create the hook manually?

**Comment by DJercic** [comment]
How did you get bitbucket to create the webhooks? I tried but somehow it's not working for me.

I start strider with SERVER_NAME and NODE_ENV variables, login to bitbucket, oauth token is created, but  webhooks aren't

**Comment by lukasberlin** [comment]
I also use  PLUGIN_BITBUCKET_APP_KEY and PLUGIN_BITBUCKET_APP_SECRET to start Strider. Webhooks were automatically created when I imported my projects from BitBucket.

**Comment by knownasilya** [comment]
There are some plans to expose the webhooks that Strider creates, so if you don't have permissions you can still add a project, and trigger manual test/deploy, but also get instructions on how to configure the webhooks once you do have permissions. See this comment: https://github.com/Strider-CD/strider-gitlab/issues/23#issuecomment-111110072

**Comment by macropin** [comment]
@knownasilya It would be good to expose the method for reinstalling the webhooks. Right now I'm having to manually delete and recreate all our projects to get the webhooks reinstalled.

**Comment by oliversalzburg** [comment]
@macropin Do you not get these buttons with the bitbucket provider?

![](http://i.imgur.com/uXn7gDS.png)

If not, then, yeah, I agree, the functions should be exposed, just like the other providers have.

**Comment by macropin** [comment]
@oliversalzburg I think the answer is no.. which page are those buttons shown? This might also be related to my issue #19

**Comment by oliversalzburg** [comment]
@macropin On the project configuration page for the provider.

![](http://i.imgur.com/TnZzupK.png)

**Comment by macropin** [comment]
@oliversalzburg This is the only option for bitbucket. And it doesn't work (#19)
<img alt="screen shot 2015-08-10 at 11 14 02 am" src="https://cloud.githubusercontent.com/assets/247192/9157913/1e4df91e-3f51-11e5-8b1b-e7a018a4b987.png">

**Comment by oliversalzburg** [comment]
This should be fixed in 33e35debf67706446d0be49745ee2905908c757d Please give it a try if you can.

Also, please note that the hooks that Strider creates are listed in the *Services* section in the project configuration on Bitbucket, not in the *Webhooks* section.

**Comment by macropin** [comment]
@oliversalzburg just tested now, and this is working for me. Thanks.

**Comment by oliversalzburg** [comment]
Awesome :+1:  :)
