### ISSUE TITLE
What is the callback url for bitbucket?

### ISSUE THREAD

**Issue by thesabbir** [Strider-CD/strider-bitbucket#20]
`/auth/github/callback` for github but I could not find one here for bitbucket.

**Comment by thesabbir** [comment]
figured out `/ext/bitbucket/oauth/callback`.
Shouldn't this be documented?

**Comment by knownasilya** [comment]
Well, it should be setup automatically, so technically you shouldn't have to know it.

**Comment by knownasilya** [comment]
Although, we do have an issue in the strider repo about exposing the urls for those that do not have admin access, so they could pass them on to someone who does. Can't find the issue at the moment.

**Comment by oliversalzburg** [comment]
@knownasilya Maybe you were thinking of https://github.com/Strider-CD/strider/issues/803
