### ISSUE TITLE
Integrate with Bitbucket Cloud 

### ISSUE THREAD

**Issue by kauegimenes** [Strider-CD/strider-bitbucket#25]
https://confluence.atlassian.com/bitbucket/integrate-your-build-system-with-bitbucket-cloud-790790968.html

**Comment by kauegimenes** [comment]
I just upgraded my Bitbucket plugin to 1.4.0 
And committed to a Bitbucket project and nothing showed up on my project commit page about the strider build.

I am missing something?

**Comment by knownasilya** [comment]
Hum, might have closed this prematurely. I think the implementation #27 only does it for PRs.

**Comment by knownasilya** [comment]
Hum, no it should work https://github.com/Strider-CD/strider-bitbucket/pull/27/files#diff-9ccb9b0bdd7e6cd41dfc6512731c2719R335

@nomean42 any ideas?

**Comment by nomean42** [comment]
@kauegimenes i think we need more information, job actually starts? is it finished? Do bitbucket account for strider have admin permissions on project?

**Comment by kauegimenes** [comment]
@nomean42 @knownasilya 
Yes the job start and finish without errors. 
The bitbucket account has admin permission.

**Comment by nomean42** [comment]
@kauegimenes ping?

**Comment by knownasilya** [comment]
Works here too, the only thing missing is the inprogress state.

**Comment by nomean42** [comment]
Cant make it in the moment, add #30
