### ISSUE TITLE
strider successfully executed, but sent to all failed bitbucket

### ISSUE THREAD

**Issue by stevenbool** [Strider-CD/strider-bitbucket#36]
I push a commit, execute successfully strider, but the message is sent bitbucket failure.
![2016-06-27 18-22-47](https://cloud.githubusercontent.com/assets/12848296/16376944/cc60a136-3c95-11e6-97ae-e12b149ddf79.png)
![2016-06-27 18-23-21](https://cloud.githubusercontent.com/assets/12848296/16376730/82234246-3c94-11e6-9f91-e62dcc5cc919.png)

**Comment by knownasilya** [comment]
What's the error on the build?

**Comment by stevenbool** [comment]
yes, past builds
![2016-06-28 09-35-42](https://cloud.githubusercontent.com/assets/12848296/16401075/d4e5eb4e-3d13-11e6-878e-01d950843d9b.png)

**Comment by stevenbool** [comment]
The error on the pull request comment  and also commits is error.

This is commits of bitbucket
