### ISSUE TITLE
Not Redirecting after granting access

### ISSUE THREAD

**Issue by ellipizle** [Strider-CD/strider-bitbucket#44]
I am stuck on the grant access page,
i am not been redirected after granting access to strider.
when i check OAuth i saw local strider been listed under OAuth integrated applications in bitbucket.
but i cant see any project on strider from bitbucket

**Comment by knownasilya** [comment]
Did you set `SERVER_NAME` correctly when trying to auth Bitbucket? If you didn't and attempted the auth, you'll have to delete the application settings for Strider in Bitbucket and try again with the correct value for `SERVER_NAME` env.

**Comment by ellipizle** [comment]
I did SERVER_NAME correct. export` SERVER_NAME=http://ci.mydomain.com`.

is the callback url necessary on the bitbucket oauth setting page

**Comment by ellipizle** [comment]
@knownasilya  
Restarts are now immutable in pm2, to update environment or conf I needed to append --update-env to restart. now everything works great. Thanks.
