### ISSUE TITLE
Push do not triggers build

### ISSUE THREAD

**Issue by felipeprov** [Strider-CD/strider-bitbucket#46]
Hi

I am using the plugin in my projects, and i saw some weird behavior.

From times to times, the push requests stops to trigger new builds, and i need to unistall and install the webhooks. 

I do not know if its just a placebo. But most of time it works...

I wanted tips about how to debug properly whats happening...

Best Regards

**Comment by knownasilya** [comment]
Did you run strider with `DEBUG=strider:*` env? Try that and see if you see anything in the logs that looks suspicious. Also, what kind of pushes, just commits?

**Comment by felipeprov** [comment]
yes, i saw the behavior pushing simple commits.
I will run with the debug turned on and monitor it

thanks

**Comment by SzymonSel** [comment]
I've setup strider /w this plugin. Manual testing works, but unfortunately they aren't triggered by webhooks. When looking into BitBucket settings, I can't seems to locate the any webhooks pointing to my strider app, although deleting/recreating webhooks in strider settings is 'successful'

**Comment by knownasilya** [comment]
@SzymonSel can you try running with the same `DEBUG=strider:*` env var and pasting the output that looks relevant?

**Comment by SzymonSel** [comment]
Sure!
> 2018-05-22T07:19:21.203Z - error: js-bson: Failed to load c++ bson extension, using pure JS version

> strider:http DELETE /myteam/myapp/api/bitbucket/hook 200 1134.143 ms - 16 +1s
> strider:http POST /myteam/myapp/api/bitbucket/hook 200 1492.772 ms - 16 +12s

![image](https://user-images.githubusercontent.com/9480863/40349289-79283950-5da6-11e8-9249-ce92045644b2.png)

**Comment by SzymonSel** [comment]
It also looks like the hooks aren't triggered by Bitbucket

**Comment by knownasilya** [comment]
Hum, no other info that looks out of place? Everything above looks rather normal.

**Comment by SzymonSel** [comment]
Nope, nothing. I did some manual POSTs with payload to the above urls, to check if strider show anything. It seems like the triggers aren't fired by BitBucket.

**Comment by knownasilya** [comment]
I'd bet they are fired, but the form of the data is changed so Strider isn't handling them.

**Comment by knownasilya** [comment]
If you can put a console.log here https://github.com/Strider-CD/strider-bitbucket/blob/master/lib/webapp.js#L293 logging the `req.body.payload` that would help identify the issue. That file should be in `node_modules/strider-bitbucket/lib/webapp.js`.

**Comment by SzymonSel** [comment]
Well they definetly were not, because I would have seen those requests in debug :)

The issue has resolved itself auto-magicaly though. Thank you for your assistance and sorry for taking your time.
Great job on StriderCD. Love it!
